version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Download dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ~/.yarn-cache
            - node_modules
      - run:
          name: Run tests
          command: >
            yarn test
            --reporter mocha-junit-reporter
            --reporter-options
            mochaFile=test-results/test-results.xml
      - store_test_results:
          path: test-results
